site_name: Diário de Cora
site_url: https://augustacora.github.io/curso_trilha_dev/
theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: amber
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - blog
  - search